<?php



function workflow_lightning_menu() {
  $items['backgrounds/lightning-review'] = array(
    'title' => 'Dynamic Backgrounds',
    'description' => 'Dynamic Backgrounds',
    'page callback' => 'workflow_lightning_entry_point',
    'access arguments' => TRUE,
  );
 return $items; 
}

function workflow_lightning_entry_point() {
  $node = workflow_lightning_next_node();
  drupal_goto(workflow_lightning_next_node($form['node']['#value']->nid));

}

function workflow_lightning_form_alter(&$form, &$form_state, $form_id) {
  global $user;
  if (in_array('site administrator', array_values($user->roles)) && $form_id == 'workflow_tab_form' ) {
    // $form['#redirect'] = workflow_lightning_next_node($form['node']['#value']->nid);
    // Sending the user back to the entry point ensures that the node they get forwarded to is fresh and hasn't been Accetped by another
    // Site Administrator.
    $form['#redirect'] = "/backgrounds/lightning-review";
  }
}

function workflow_lightning_next_node($not = NULL) {
  $sql = "select nid from workflow_node where state_name='background_approvals_review' && nid != %d ORDER BY stamp ASC;";
  $node = node_load(db_result(db_query($sql, $not)));
  if (!$node) {
    return "backgrounds/review";
  }
  else {
    return $node->path;  
  }
}
