<?php

function workflow_lightning_form_alter(&$form, &$form_state, $form_id) {
  global $user;
  if (in_array('site administrator', array_values($user->roles)) && $form_id == 'workflow_tab_form' ) {
    $form['#redirect'] = workflow_lightning_next_node($form['node']['#value']->nid);
  }
}

function workflow_lightning_next_node($not = NULL) {
  $sql = "select nid from workflow_node where state_name='background_approvals_review' && nid != %d ORDER BY stamp ASC;";
  $node = node_load(db_result(db_query($sql, $not)));
  if (!$node) {
    return "backgrounds/review";
  }
  else {
    return $node->path;  
  }
}
